parserOptions:
  ecmaVersion: 2015
  sourceType: 'module'
  parser: "babel-eslint"

root: true

env:
  es6: true
  browser: true
  commonjs: true,
  node: true

extends: ["plugin:vue/essential", "htmlacademy/es6"]

